name: luacheck

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Use "Factorio Mod luacheck" from the marketplace
    - name: Factorio Mod luacheck
      uses: Roang-zero1/factorio-mod-luacheck@v1.1.0
      with:
          # URL to the luacheckrc configuration file to be used during checking.
          # Per https://github.com/Roang-zero1/factorio-mod-luacheck/issues/2 - an empty string will use the project's .luacheckrc
          luacheckrc_url: "" # optional, default is https://raw.githubusercontent.com/Nexela/Factorio-luacheckrc/0.17/.luacheckrc
